### ISSUE TITLE
v3. Validator page. Number 3 behind validator name

### ISSUE THREAD

**Issue by El-Jay-Crypto** [BitCannaGlobal/WeedWallet#169] opened 2023-11-13 12:08 UTC
![image](https://github.com/BitCannaGlobal/WeedWallet/assets/22987129/073b3320-770b-45c7-b2c8-a2904142ffae)
Behind the name of every validator, there is a number 3.

**Comment by atmoner** [comment] 2023-11-13 21:05
Uuuhu! Eagle eye :100:  

This is a variable that I had to use to debug the status of the validator!
The problem is [this line](https://github.com/BitCannaGlobal/WeedWallet/blob/main/pages/validators/%5Bid%5D.vue#L24), do you want to fix it?

**Comment by El-Jay-Crypto** [comment] 2023-11-13 22:49
PR send

**Comment by atmoner** [comment] 2024-01-08 17:55
Fixed in this commit: https://github.com/BitCannaGlobal/WeedWallet/commit/6fb0822dcd815eb3e02f4cb7c43cfc7698271e79

**Comment by RaulBernal** [comment] 2024-01-16 10:43
Fixed! 
<img width="1026" alt="image" src="https://github.com/BitCannaGlobal/WeedWallet/assets/3751926/ca51c39c-a7dc-49c6-8cb0-a90fbf11a1e6">

**Closed by RaulBernal** 2024-01-16 10:43 UTC
Labels: bug, good first issue, Can be tested
